// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDusarxIf0sigPD60w4ef9heRsrdNWm4RQ',
    appId: '1:864933183695:web:5bf823c2a2f0a4888177ba',
    messagingSenderId: '864933183695',
    projectId: 'authentication-firebase-db29b',
    authDomain: 'authentication-firebase-db29b.firebaseapp.com',
    storageBucket: 'authentication-firebase-db29b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA-62VOcCviYjeBmB_gzYeSKhw8iz3uHI',
    appId: '1:864933183695:android:18dfcf2c48d183bf8177ba',
    messagingSenderId: '864933183695',
    projectId: 'authentication-firebase-db29b',
    storageBucket: 'authentication-firebase-db29b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCawWdRn199g7Y0G317Ah_4insk99rI4EY',
    appId: '1:864933183695:ios:44c0a83c7fd344b68177ba',
    messagingSenderId: '864933183695',
    projectId: 'authentication-firebase-db29b',
    storageBucket: 'authentication-firebase-db29b.appspot.com',
    iosBundleId: 'com.example.authenticationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCawWdRn199g7Y0G317Ah_4insk99rI4EY',
    appId: '1:864933183695:ios:03cf2bc28c82e2c58177ba',
    messagingSenderId: '864933183695',
    projectId: 'authentication-firebase-db29b',
    storageBucket: 'authentication-firebase-db29b.appspot.com',
    iosBundleId: 'com.example.authenticationFirebase.RunnerTests',
  );
}
